export const MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024 * 1024; // 10GB
export const STREAM_URL_TTL_SECONDS = 3600;
export const DOWNLOAD_URL_TTL_SECONDS = 300;
export const VIDEO_PROCESSING_JOB_NAME = 'video.process';
export const VIDEO_PROCESSING_ATTEMPTS = 3;
export const VIDEO_PROCESSING_BACKOFF_DELAY_MS = 2000;

export const VIDEO_ERROR_REASONS = {
  PROCESSING_FAILED: 'PROCESSING_FAILED',
  INVALID_FORMAT: 'INVALID_FORMAT',
  TIMEOUT: 'TIMEOUT',
} as const;
